### ISSUE TITLE
Converting a fraction of one BTC to USD seems not supported

### ISSUE THREAD

**Issue by yanalanhe** [rehhouari/exchange#2]
Converting a fraction of 1BTC to USD got same results as the one of converting 1BTC.

For instance, the following conversions and results were performed on 2023-07-05:

```
ex := exchange.New("BTC")
result, err := ex.ConvertTo("USD", 0.000330) //  30147.44. Not correct. Expected result should be around 9.95 (USD).
result, err := ex.ConvertTo("USD", 1)             // 30147.44. Correct.
result, err := ex.ConvertTo("USD", 1.5)          // 46074.39. Correct.
```
What are the proper method and snippet to convert a fraction of one BTC to USD?

**Comment by rehhouari** [comment]
hey sorry about the problem, im trying to find the source and it seems to be a problem in the API, can you confirm this?
https://api.exchangerate.host/convert?from=BTC&to=USD&amount=0.000330

i think it doesn't support this low of a number which in the case of crypto makes it unusable :/

**Comment by yanalanhe** [comment]
Thanks for the response. I ran the above URL to convert 0.00033BTC to USD and confirmed returning null result. But I tried other fractions and found that  converting any fraction greater than or equal 0.015 BTC worked. But converting fraction smaller than 0.015 BTC returned null result.

**Comment by rehhouari** [comment]
oh thats a bummer, sadly I'm not in control over that API just this client.
Here is the repo for the API it may have more info or you can make an issue l there
https://github.com/Formicka/exchangerate.host
